apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app: web-server
    home-task: "unity"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
        home-task: "unity"
    spec:
      containers:
      - name: web-server
        image: ghcr.io/yaronkalatian/web-server:IMAGE_TAG
        env:
        - name: KAFKA_BOOTSTRAP
          value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_TOPIC
          value: purchases
        - name: CM_API_BASE
          value: http://customer-management.default.svc.cluster.local:3001
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    home-task: "unity"
spec:
  selector:
    app: web-server
  ports:
    - port: 3000
      targetPort: 3000